# compile:
# d2 --font-regular=C:\Windows\Fonts\times.ttf --font-bold=C:\Windows\Fonts\timesbd.ttf --font-italic=C:\Windows\Fonts\timesi.ttf -t 1 -w .\3-tier-architecture.d2 .\3-tier-architecture.png
direction: right
UI -> API -> DB
UI <- API <- DB