name: tests
run-name: Running Tests
on: [push]
jobs:
  check-pep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install pip dependencies
        run: pip install -r requirements.txt
      
      - name: Lint formatting
        run: black --check backupclient
      
      - name: Check PEP
        run: flake8 backupclient

      - name: check Security vulnerabilites
        run: bandit backupclient

      
      
